theme = "dracula"

[editor]
auto-format = false
rulers = [80, 120]
trim-trailing-whitespace = true
trim-final-newlines = true

[editor.file-picker]
hidden = false

[keys.normal.space]
L = ":theme alucard"
D = ":theme dracula"
